trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsRegion: 'us-east-1'
  awsEcrRepo: '463657084111.dkr.ecr.us-east-1.amazonaws.com/clean-api-core-framework'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet build --configuration Release
      displayName: 'Build .NET Project'
      workingDirectory: 'clean-api-core-framework'

    # Login to AWS ECR
    - task: AWSCLI@1
      displayName: 'Login to AWS ECR'
      inputs:
        awsCredentials: 'aws-ecr-connection'  # Azure DevOps service connection
        regionName: '$(awsRegion)'
        command: 'ecr'
        arguments: 'get-login-password --region $(awsRegion) | docker login --username AWS --password-stdin $(awsEcrRepo)'

    # Build Docker Image
    - script: |
        docker build -t $(awsEcrRepo):$(tag) .
      displayName: 'Build Docker Image'

    # Push Docker Image
    - script: |
        docker push $(awsEcrRepo):$(tag)
      displayName: 'Push Docker Image to ECR'
